first_project/accounts/urls.py
from django.conf.urls import url

from .import views

app_name='accounts'

urlpatterns=[
    url(r'^signup/$',views.signup_view,name='signup'),
    url(r'^login/$',views.login_view,name="login"),
    url(r'^logout/$',views.logout_view,name="logout"),
]

first_project/articles/urls.py
from django.conf.urls import url
from django.urls import path
from .import views

app_name='articles'
urlpatterns = [
    # path('admin/', admin.site.urls),
    # url(r'^$',views.index,name='index'),
    # url(r'^about/$',views.about),
    url(r'^$',views.article_list,name='list'),
    url(r'^create/$',views.article_create,name='create'),
    url(r'^search/$',views.search_view,name='search'),
    url(r'^upload/$',views.upload_resume,name='upload'),
    url(r'^board/',views.PersonalBoard.as_view(),name='board'),
    path('candidate/<int:pk>',views.CandidateDetailView.as_view(),name='detail'),
    path('survey/<int:pk>',views.OrgSurvey,name='survey'),
    path('update/<int:pk>',views.CandidateUpdateView.as_view(),name='candidate-update'),
    path('ajax/load-depts/',views.load_depts,name='ajax_load_depts'),
    url(r'^(?P<slug>[\w-]+)/$',views.article_detail,name="detail"),
    
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from .import view
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views


urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^$',views.index,name='index'),
    url(r'^articles/',include('articles.urls')), ## to look up the articles app to include the urls inside the file
    url(r'^about/$',view.about),
    url(r'^$',article_views.article_list,name='home'),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^positions/',include('positions.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first_project/articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from positions.models import Client,Position


# Create your models here.
class CandidateInfo(models.Model):
    id=models.IntegerField(primary_key=True)
    name=models.CharField(max_length=264)
    phone_number=models.CharField(max_length=264)
    email=models.EmailField()
    work_experience=models.IntegerField(blank=True,null=True)
    related_work_experience=models.IntegerField(blank=True,null=True)
    leadership_experience=models.IntegerField(blank=True,null=True)
    area_of_focus=models.CharField(max_length=264,blank=True,null=True)
    applied_position=models.CharField(max_length=264,blank=True,null=True)
    bytedance_application_link=models.URLField(blank=True,null=True)
    linkedin=models.URLField(blank=True,null=True)
    hunter=models.CharField(max_length=264,blank=True,null=True)
    applied_location=models.CharField(max_length=264,blank=True,null=True)
    resume_content=models.TextField(default=None,blank=True,null=True)
    resume_file=models.FileField(default=None,blank=True,null=True)
    location=models.CharField(max_length=264,blank=True,null=True)
    create_date=models.DateTimeField(null=True,blank=True,auto_now=True)

    applied_company=models.ForeignKey(Client,on_delete=models.SET_DEFAULT,blank=True,null=True,default='')
    client_position=models.ForeignKey(Position,on_delete=models.SET_DEFAULT,blank=True,null=True,default='')
    flag_experience=models.BooleanField(default=False)
    status=models.CharField(max_length=64,null=True)
    resume_submited_date=models.DateField(null=True)
    duplicated=models.BooleanField(default=False)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('articles:detail',kwargs={'pk':self.pk})
    def get_current_company(self):
        return CandidateExperience.objects.filter(canid=self,expid=0)[0].company
    def get_current_position(self):
        return CandidateExperience.objects.filter(canid=self,expid=0)[0].position


class CandidateEdu(models.Model):
    canid=models.ForeignKey(CandidateInfo,on_delete=models.CASCADE)
    eduid=models.IntegerField()
    university=models.CharField(max_length=264,blank=True,null=True)
    degree=models.CharField(max_length=264,blank=True,null=True)
    major=models.CharField(max_length=264,blank=True,null=True)
    end_date=models.CharField(max_length=264,blank=True,null=True)
    start_date=models.CharField(max_length=264,blank=True,null=True)
    def __str__(self):
        return (str(self.canid.id)+' '+self.canid.name+' '+str(self.eduid))

class CandidateExperience(models.Model):
    canid=models.ForeignKey(CandidateInfo,on_delete=models.CASCADE)
    expid=models.IntegerField()
    start_date=models.CharField(max_length=264,blank=True,null=True)
    end_date=models.CharField(max_length=264,blank=True,null=True)
    company=models.CharField(max_length=264,blank=True,null=True)
    position=models.CharField(max_length=264,blank=True,null=True)
    job_description=models.TextField(blank=True,null=True)
    def __str__(self):
        return (str(self.canid.id)+' '+self.canid.name+' '+str(self.expid))

class Article(models.Model):
    title =models.CharField(max_length=100)
    slug = models.SlugField()
    body =models.TextField()
    # resume = models.FileField()
    date =models.DateTimeField(auto_now_add= True)
    thumb=models.ImageField(default= 'default.png',blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    # add in author later

    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:50]+'...'


class RequestLog(models.Model):
    id=models.IntegerField(primary_key=True,auto_created=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    content_requst=models.CharField(null=True,max_length=512)
    applied_positon_request=models.CharField(null=True,max_length=512)
    recent_work_request=models.CharField(null=True,max_length=512)
    titles_request=models.CharField(null=True,max_length=512)
    companies_request=models.CharField(null=True,max_length=264)
    location_request=models.CharField(null=True,max_length=264)
    min_work_length_request=models.IntegerField(null=True)
    max_work_length_request=models.IntegerField(null=True)
    min_leadership_length_request=models.IntegerField(null=True)
    max_leadership_length_request=models.IntegerField(null=True)
    time=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return (str(self.user.first_name)+' '+str(self.time))

class OrgCompany(models.Model):
    
    name=models.CharField(max_length=64,primary_key=True)
    def __str__(self):
        return(self.name)

class OrgDept(models.Model):
    parent=models.ForeignKey(OrgCompany,on_delete=models.CASCADE)
    name=models.CharField(max_length=256)
    def __str__(self):
        return(self.parent.name+' '+self.name)

class OrgSurvey(models.Model):
    company=models.ForeignKey(OrgCompany,on_delete=models.SET_DEFAULT,default='')
    department=models.ForeignKey(OrgDept,on_delete=models.SET_DEFAULT,default='')
    other_department=models.CharField(max_length=256,null=True,blank=True)
    candidate=models.ForeignKey(CandidateInfo,on_delete=models.CASCADE)
    team=models.CharField(max_length=128,null=True,blank=True)
    self_provide_dept=models.CharField(max_length=128,null=True,blank=True)
    team_size=models.IntegerField(null=True)
    base_expectation=models.IntegerField(null=True)
    total_expectation=models.IntegerField(null=True)
    will_to_china=models.CharField(max_length=8,
        choices=[('y','Yes'),('n','No'),('depends','Depends')]
    )
    team_management=models.CharField(max_length=64,
        choices=[
            (1,'IC'),
            (2,'Senior IC role'),
            (3,'Team Lead/Manager'),
            (4,'Department Head/Manager/Sr. Manager/Director/Sr. Director'),
            (5,'GM of Business Unit/VP/SVP'),
            (6,'C-level')
        ]
    )
    people_in_lead=models.IntegerField(null=True)
    reason_for_departure=models.CharField(max_length=64,
    choices=[
        (1,'Good location'),
        (2,'Package increase'),
        (3,'Company value & culture'),
        (4,'Product & tech capability'),
        (5,'Head or colleague'),
        (6,'Level promotion'),
        (7,'Lead a larger team and more responsibilities'),
        (8,'Other: please specify below')
    ]
    
    )
    other_reason_for_departure=models.CharField(max_length=256,null=True,blank=True)
# class CandidateStatus(models.Model):
#     id=models.IntegerField(primary_key=True,auto_created=True)
#     candidate=models.ForeignKey(CandidateInfo,on_delete=models.CASCADE)
#     applied_company=models.ForeignKey(Client,on_delete=models.SET_DEFAULT,blank=True,null=True,default='')
#     client_position=models.ForeignKey(Position,on_delete=models.SET_DEFAULT,blank=True,null=True,default='')
#     flag_experience=models.BooleanField()
#     status=models.CharField(max_length=64)
#     resume_submited_date=models.DateField()
    # resume_submited_date=models.CharField(max_length=64)
# class ClientCompany(models.Model):
#     name=models.CharField(max_length=64)
#     def __str__(self):
#         return self.name

# class Positions(models.Model):
#     id=models.IntegerField(primary_key=True,auto_created=True)
#     company=models.ForeignKey(ClientCompany,on_delete=models.CASCADE)
#     name=models.CharField(max_length=64)
#     location=models.CharField(max_length=64,null=True)
#     account_manager=models.CharField(max_length=128,null=True)
#     tips=models.TextField(default=None,blank=True,null=True)
#     description=models.TextField(default=None,blank=True,null=True)
#     file=models.FileField(blank=True)
#     def __str__(self):
#         return(str(self.id)+' '+self.company.name+' '+self.name)      

first_project/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h2 style="text-align: center;">Make an Announcement</h2>
        <form class="site-form" action="{% url 'articles:create'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>
    </div>
</div>
{% endblock %}

first_project/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content%}

<div class="article-detail">
    <div class="article">
        <h2>{{article.title}}</h2>
        <p>{{article.body}}</p>
        <p> {{article.date}}</p>
    </div>
</div>

{% endblock %}

first_project/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
     <h1 style="text-align: center;"> Welcome to the Home page!</h1>
     <h2> Latest Announcements</h2>
     <div class="listings">
         {% for article in listings %} 
            <div class="article">
                <h3><a href="{%url 'articles:detail' article.slug%}">{{article.title}}</article></a></h3>
                <p>{{article.snippet}}</article></p>
                <p>{{article.date}}</p>
            </div>
         {% endfor %}
     </div>
    </div>
</div>
     <div class="row"> 
         <div class="col-md-12">
             {% if listings.has_other_pages %}
                <ul class="pagination">
                    {% if listings.has_previous %}
                        <li class="page-item">
                            <a href="?page={{listings.previous_page_number}}" class="page-link"> &laquo</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" >&laquo</a>
                        </li>
                    {% endif %} 
                    {% for i in listings.paginator.page_range %}
                        {% if listings.number == i %}
                        <li class="page-item active">
                            <a  class="page-link">{{i}}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a href="?page={{i}}" class="page-link">{{i}}</a>
                        </li>
                        {% endif%}
                    {% endfor %}
                    {% if listings.has_next %}
                    <li class="page-item">
                        <a href="?page={{listing.previous_page_number}}" class="page-link"> &raquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" >&raquo;</a>
                    </li>
                {% endif %} 
                </ul>
             {% endif %}
         </div>

     </div>
{% endblock %}

first_project/articles/templates/articles/candidate.html
{% extends 'base_layout.html' %}
{% block content %}

<div class="container" style="color:#8d99ae;">
   <div class="col-lg-11">
    <div class="jumbotron">
        <div class=" row">
            <div class="col-lg-4"></div>
            <div class="col-lg-4">
                <h2 style="text-align: center;"> <b>{{ candidate.name}} </b></h2>
            </div>
            
        </div>
       
        <h3> Position Details </h3>
            <br>
            <div class="container">
                <div class="col-lg-4">Client: {{ candidate.applied_company }}</div>
                <div class="col-lg-4">Position: {{ candidate.client_position }}</div>
                <div class="col-lg-4">Status: {{ candidate.status}}</div>
            </div>
            <br>
                 <div class="container">
                <div class="col-lg-4">Resume submited date: {{ candidate.resume_submited_date}}</div>

     {% if candidate.resume_file %}
     <div class="col-lg-4"><a  href="{{candidate.resume_file.url}}"> Download Resume</a></div>
   {% endif %}  
            </div>
      
         <hr><br>
        <h3> Contact Details </h3>
            <br>
            <div class="container">
                <div class="col-lg-4">Name: {{ candidate.name }}</div>
                <div class="col-lg-4">Phone Number: {{ candidate.phone_number }}</div>
                <div class="col-lg-4">Email: {{ candidate.email}}</div>
                <div class="col-lg-4">Location: {{ candidate.location}}</div>
                <div class="col-lg-4">Flag experience: {{ candidate.flag_experience}}</div>
            </div>
         <hr><br>
         <h3> Education Background </h3>
            <br>
            {% for e in edu %}
            <div class="container">
                
                <div class="col-lg-4">Degree: {{ e.degree }}</div>
                <div class="col-lg-4">Major: {{ e.major }}</div>
                <div class="col-lg-4">Date: {{ e.start_date }} ~ {{ e.end_date }}</div>
                <div class="col-lg-12">University: {{ e.university}}</div>
            </div>
            {% endfor %}
         <hr><br>
         <h3> Work Experience Overview: </h3>
            <br>
            <div class="container">
                <div class="col-lg-4">Work experience: {{ candidate.work_experience }} years</div>
                <div class="col-lg-4">Related work experience: {{ candidate.related_work_experience }} years</div>
                <div class="col-lg-4">Leadership experience: {{ candidate.leadership_experience }} years</div>
                <div class="col-lg-12">Area of focus: {{ candidate.area_of_focus }}</div>
            </div>
         <hr><br>
         <h3> Work Experience:  </h3>
            <br>
            {% for e in experience %}
            <div class="container">
                <div class="col-lg-4">Company: {{ e.company}}</div>
                <div class="col-lg-4">Position: {{ e.position }}</div>
                <div class="col-lg-4">Time: {{ e.start_date }} ~ {{ e.end_date }}</div>
                <br>
                <br>
                <div class="col-lg-6"> Description: {{ e.job_description}}</div>
                
            </div>
            <hr>
            {% endfor %}
        <br>

    </div>
</div> 
<div class="col-lg-1">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <a class="btn btn-default" href="{% url 'articles:survey' pk=candidate.pk %}"> Survey</a>
    <br>
    <br>
    <br>
    <a class="btn btn-default" href="{% url 'articles:candidate-update' pk=candidate.pk %}">Update</a>
</div>
</div>




{% endblock %}

first_project/articles/templates/articles/candidate_update.html
{% extends 'base_layout.html' %}
{% load static %}

{% block js %}

<!-- <script src="https://code.jquery.com/jquery-3.5.1.js" 
integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" 
crossorigin="anonymous"></script> -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>
$(function () {
      $("#id_resume_submited_date").datepicker(); });
   
  </script>
{% endblock %}


{% block content %}
    <div class="container">
      <div class="jumbotron">
        <h2 style="text-align:center">Update the Candidate Info</h2>
        <form method="POST" enctype="multipart/form-data">
           
            {% csrf_token %}
            {{ form.as_p}}
  
            <input type="submit" value="Update">
        </form>
      </div>
    </div>
{% endblock %}

first_project/articles/templates/articles/dept_dropdown.html
<option value="">---------</option>
{% for dept in departments %}
<option value="{{ dept.name }}">{{ dept.name }}</option>
{% endfor %}

first_project/articles/templates/articles/email_success.html
{% extends 'base_layout.html' %}
{% block content %}
<br>
<br>
<br>
<div class="container">
    <div class="col-lg-3"></div>
    <div class="col-lg-9">
    <h2> Great, {{request.user| title}}! </h2>
      <h2> Your alert email to {% for hunter in hunters %} {{hunter|title }}{% endfor %} is on the way!</h2>
</div>
</div>


{% endblock %}

first_project/articles/templates/articles/enter_keywords.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
     <h1 style="text-align: center;"> Please enter at least one keyword to start searching</h1>
     <div>
</div>
{% endblock %}

first_project/articles/templates/articles/personal_board.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}
<div class="container">
    
   
<br>

</div>
<div class="container">

 <table class="table table-hover" id='result-table'>
     <thead>
         <th>Candidate</th>
         <th>Client Company</th>
         <th>Current Company</th>
         <th>Current Position</th>
         <th>submited date</th>
         <th>flag experience</th>
         <th>Pipline status</th>
         <th>Survey</th>
        
     </thead>

     {% for person in candidates %} 
   
     <tr>
        
         <!-- <td><a href="{{ exp.canid.bytedance_application_link }}">{{exp.canid.name}}</a></td> -->
         <td><a href="{{ person.get_absolute_url }}">{{ person.name }}</a> </td>
         <td>{{ person.applied_company }}</td>
         <td>{{ person.get_current_company }}</td>
         <td>{{ person.get_current_position }}</td>
         <!-- <td>{{ person.client_position }}</td> -->
         <td>{{ person.resume_submited_date }}</td>
         <td>{{ person.flag_experience }}</td>
         <td><a href="{% url 'articles:candidate-update' pk=person.pk %}">{{ person.status }}</a></td>
        <td><a class='btn btn-default btn-sm'href="{% url 'articles:survey' pk=person.pk %}"></a></td>
         <!-- <td>{{ exp.canid.location }}</td>  -->
     

         <!-- <td>{{exp.expid}}</td>
         <td>{{exp.company}}</td>
         <td>{{exp.position}}</td>
         <td>{{exp.start_date}}</td> 
         <td>{{exp.canid.hunter}}</td> -->
         <!-- <td>{{profile.experience|slice:"1"}}</td>
         <td>{{profile.experience|slice:'1'}}</td> -->
     </tr>
     
     {% endfor %}


 </table>
</form>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js" 
integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" 
crossorigin="anonymous"></script>
<script src="{% static 'check_all.js' %}"></script>


{% endblock %}

first_project/articles/templates/articles/search_result.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}
<div class="container">
    
    <form action="{% url 'articles:search'%}" method="POST">
        <div class="input-group">
            <div class="row">
            <input type="text" name='email_title' placeholder="Enter position here"></input>
            <input type="submit" class="submit" value="Send Emails" id='submit-position'> </input>
        </div>
            {% csrf_token %}
<br>
<div class="container">
    <input type="checkbox" name="select-all" id="select-all" />
    <label for="select-all">Check All</label>
</div>
</div>
<div class="container">

 <table class="table table-hover" id='result-table'>
     <thead>
         <th>select</th>
         <th>id</th>
         <th>name</th>
         <th>recruiter</th>
         <th>bytedance application position</th>
         <th>work experience</th>
         <th>leadership experience</th>
         <th>most recent company</th>
         <th>most recent title</th>
     </thead>

     {% for exp in exps %} 
        {% if exp.expid == 0 %}
     <tr>
         <td><input type="checkbox" name='checks' value='{{ exp.canid.id}}'></td>
         <td>{{ exp.canid.id }}</td>
         <td><a href="{{ exp.canid.bytedance_application_link }}">{{exp.canid.name}}</a></td>
         <td>{{ exp.canid.hunter|title}}</td>
         <td>{{ exp.canid.applied_position}}</td>
         <td>{{ exp.canid.work_experience }}</td>
         <td>{{ exp.canid.leadership_experience}}</td>
         <!-- <td>{{ exp.canid.location }}</td>  -->
         <td>{{ exp.company}}</td>
         <td>{{ exp.position }}</td>

         <!-- <td>{{exp.expid}}</td>
         <td>{{exp.company}}</td>
         <td>{{exp.position}}</td>
         <td>{{exp.start_date}}</td> 
         <td>{{exp.canid.hunter}}</td> -->
         <!-- <td>{{profile.experience|slice:"1"}}</td>
         <td>{{profile.experience|slice:'1'}}</td> -->
     </tr>
        {% endif %}
     {% endfor %}


 </table>
</form>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js" 
integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" 
crossorigin="anonymous"></script>
<script src="{% static 'check_all.js' %}"></script>


{% endblock %}

first_project/articles/templates/articles/survey.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="container">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
    <div class="jumbotron">
        <h2 style="text-align: center;color:#457B9D">Interview Note for {{candidate}}</h2>
        <br>
        
        <form method="post" id='surveyform' data-depts-url="{% url 'articles:ajax_load_depts'  %}" novalidate>
          {% csrf_token %}
          
          <h4>Company</h4>
          {{ form.company}}
          <br>
          <h4>Which vertical/department - supervisor does he/she belong to?</h4>
          {{ form.department}}
          <br>
          <h4>Explain if not above - please specify the department & supervisor names</h4>
          {{ form.other_department}}
          <br>
          <h4>Which team is he/she on?</h4>
          {{ form.team}}
          <br>
          <h4>How many people are there in his/her team?</h4>
          {{ form.team_size }}
          <br>
          <h4>What's his/her expectation on the base in $K?</h4>
          {{ form.base_expectation}}
          <br>
          <h4>What's his/her expectation on the total package in $K?</h4>
          {{ form.total_expectation}}
          <br>
          <h4>Willingness to relocate to China (only for bilingual candidates)</h4>
          {{form.will_to_china}}
          <br>
          <h4>Team management</h4>
          {{ form.team_management}}
          <br>
          <h4>If >= Team Lead/Manager, how many people does he/she lead?</h4>
          {{form.people_in_lead}}
          <br>
          <h4>Reasons for departure</h4>
          {{form.reason_for_departure}}
          <br>
          <h4>Other reason for departure</h4>
          {{form.other_reason_for_departure}}
          <br>
          <button type="submit">Save</button>
         
        </form>
            </div>
        
        </div></div>
    <div class="col-lg-2"></div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_company").change(function () {
      var url = $("#surveyform").attr("data-depts-url");  // get the url of the `load_cities` view
      var companyId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'company': companyId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_department").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>
{% endblock %}

first_project/articles/templates/articles/upload_resume.html
{% extends 'base_layout.html' %}
{% load static %}

{% block js %}

<!-- <script src="https://code.jquery.com/jquery-3.5.1.js" 
integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" 
crossorigin="anonymous"></script> -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>
$(function () {
      $("#id_resume_submited_date").datepicker(); });
   
  </script>
{% endblock %}


{% block content %}
    <div class="container">
      <div class="jumbotron">
        <h2 style="text-align:center">Upload a candidate</h2>
        <form class="site-form" action="{% url 'articles:upload'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h3> Position Details </h3>
            <br>
            <div class="container">
                <div class="col-lg-4">Client: {{ formResume.applied_company }}</div>
                <div class="col-lg-8">Position: {{ formResume.client_position }}</div>
               
            </div>
            <br>
                 <div class="container">
                  <div class="col-lg-4">Resume submited date: {{ formResume.resume_submited_date }}</div>
                  <div class="col-lg-4">Upload Resume: {{ formResume.resume_file }}</div>
                  <div class="col-lg-4">Duplicated: <br> {{ formResume.duplicated}}</div>
                  
          </div>
            <br>
            <hr>
            <h3> Contact Details </h3>
                <br>
                <div class="container">
                    <div class="col-lg-4">Name: {{ formResume.name }}</div>
                    <div class="col-lg-4">Phone Number: {{ formResume.phone_number }}</div>
                    <div class="col-lg-4">Email: {{ formResume.email}}</div>
                    <div class="col-lg-4">Location: {{ formResume.location}}</div>
                    <div class="col-lg-4">Linkedin: {{ formResume.linkedin}}</div>
                    <div class="col-lg-4">Flag experience: <br> {{ formResume.flag_experience}}
                   
                </div> 
                </div>
             <hr>
             <h3> Education Background </h3>
        <br>
        <div class="container">
            
            <div class="col-lg-4">Degree: {{ formEdu.degree }}</div>
            <div class="col-lg-4">Major: {{ formEdu.major }}</div>
            
            <div class="col-lg-4">University: {{ formEdu.university}}</div>
        </div>
             <h3> Work Experience Overview: </h3>
             <br>
             <div class="container">
                 <div class="col-lg-4">Work experience (yrs): {{ formResume.work_experience }} </div>
                 <div class="col-lg-4">Related work experience (yrs): {{ formResume.related_work_experience }} </div>
                 <div class="col-lg-4">Leadership experience (yrs): {{ formResume.leadership_experience }} </div>
                 <div class="col-lg-12">Area of focus: {{ formResume.area_of_focus }}</div>
             </div>
          <hr><br>
          <h3> Work Experience:  </h3>
          <div class="container">
            <div class="col-lg-4">Company: {{ formExp.company}}</div>
            <div class="col-lg-4">Position: {{ formExp.position }}</div>
            <div class="col-lg-2">Start: {{ formExp.start_date }}  </div>
            <div class="col-lg-2">End: {{ formExp.end_date }} </div>
            <br>
            <br>
            <div class="col-lg-6"> Description: {{ formExp.job_description}}</div>
            
        </div>
        <hr>
            
        
  
            <input type="submit" value="Create">
        </form>
      </div>
    </div>
{% endblock %}