first_project/accounts/urls.py
from django.conf.urls import url

from .import views

app_name='accounts'

urlpatterns=[
    url(r'^signup/$',views.signup_view,name='signup'),
    url(r'^login/$',views.login_view,name="login"),
    url(r'^logout/$',views.logout_view,name="logout"),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from .import view
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views


urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^$',views.index,name='index'),
    url(r'^articles/',include('articles.urls')), ## to look up the articles app to include the urls inside the file
    url(r'^about/$',view.about),
    url(r'^$',article_views.article_list,name='home'),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^positions/',include('positions.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first_project/positions/urls.py
from django.conf.urls import url
from django.urls import path
from .import views

app_name='positions'
urlpatterns = [
    # path('admin/', admin.site.urls),
    # url(r'^$',views.index,name='index'),
    # url(r'^about/$',views.about),
    # url(r'^$',views.article_list,name='list'),
    # url(r'^create/$',views.article_create,name='create'),
    # url(r'^search/$',views.search_view,name='search'),
    # url(r'^upload/$',views.upload_resume,name='upload'),
    # url(r'^(?P<slug>[\w-]+)/$',views.article_detail,name="detail"),
    
    path('',views.PositionListView.as_view(),name='position-list'),
    path('create/',views.PositionCreateView.as_view(),name='position-create'),
    path('<int:pk>/',views.PositionDetailView.as_view(),name='position-detail'),
    path('update/<int:pk>',views.PositionUpdateView.as_view(),name='position-update'),
    path('delete/<int:pk>',views.PositionDeleteView.as_view(),name='delete')
   
]

first_project/positions/models.py
from django.db import models
from django.urls import reverse


class Client(models.Model):
    name=models.CharField(max_length=64)
    def __str__(self):
        return self.name
# Create your models here.
class Position(models.Model):
    # id=models.IntegerField(primary_key=True)
    company=models.ForeignKey(Client,on_delete=models.CASCADE)
    name=models.CharField(max_length=64)
    location=models.CharField(max_length=64,null=True)
    account_manager=models.CharField(max_length=128,null=True)
    recruiter=models.CharField(max_length=64,null=True)
    tips=models.TextField(default=None,blank=True,null=True)
    description=models.TextField(default=None,blank=True,null=True)
    file=models.FileField(blank=True)
    def __str__(self):
        return(str(self.id)+' - '+self.company.name+' '+self.name)  
    def get_absolute_url(self):
        return reverse('positions:position-detail',kwargs={'pk':self.pk})

first_project/positions/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse
# from .models import Article,CandidateInfo,CandidateEdu,CandidateExperience,RequestLog
from django.contrib.auth.decorators import login_required
from .import forms
from django.views.generic import(
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView
)

from .models import Position,Client
# Create your views here.

class PositionListView(ListView):
    model=Position
    # paginate_by=30
    context_object_name='position_list'
    template_name='positions/position_list.html'
    queryset=Position.objects.all()
    
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(PositionListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['clients'] = Client.objects.all()
        return context

class PositionDetailView(DetailView):
    model=Position
    template_name='positions/position_detail.html'
    context_object_name='position'
    # def get_object(self):
    #     id_=self.kwargs.get('id')
    #     return get_object_or_404(Position,id=id_)

class PositionCreateView(CreateView):
    model=Position

    template_name='positions/position_create.html'
    fields=['company','name','location','account_manager','recruiter','tips','description','file']
    context_object_name='form'

class PositionUpdateView(UpdateView): 
    model=Position
    template_name='positions/position_update.html'
    context_object_name='form'
    fields=['name','account_manager','recruiter','tips','description','file']

class PositionDeleteView(DeleteView):
    model=Position
    success_url= reverse_lazy('positions:position-list')
    

first_project/positions/templates/positions/position_confirm_delete.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">
    <br>
    <br>
    <h1 style="text-align: center;color: #457b9d;"> Delete {{position.name}} ?</h1>
    <br>
    <br>
    <form method="POST">
        {% csrf_token %}
        <div class="col-lg-4"></div>
        <div class="col-lg-2">
        <input type="submit"  class="btn btn-danger" value="Delete"></input></div>
        <div class="col-lg-2">

        <a href="{% url 'positions:position-detail' pk=position.pk %}"> Cancel</a>
    </div>
</div>
    <div class="col-lg-4"></div>
    </form>
</div>
{% endblock %}

first_project/positions/templates/positions/position_create.html
{% extends 'base_layout.html' %}
{% block content %}



<div class="container">
    <div class="col-lg-1"></div>
    <div class="col-lg-10">
   <div class="jumbotron">
    <h2 style="text-align: center;"> Post a position</h2>
    <br>
    <br>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- ['company','name','location','account_manager','recruiter','tips','description','file'] -->
    <div class="row">
        
        <div class="col-lg-4"><label for='id_company'>Company:    </label> {{ form.company }}</div>
        <div class="col-lg-4"><label for='id_name'>Position:     </label>  {{ form.name }}</div>
        <div class="col-lg-4"><label for='id_location'>Location:    </label>  {{ form.location }}</div>
    </div>
    <br>
    <br>

    <div class="row">
        <div class="col-lg-4"><label for='id_account_manager'>AM:   </label>{{ form.account_manager }}</div>
        <div class="col-lg-4"><label for='id_company'>Company:   </label>{{ form.recruiter }}</div>
    </div>
    <hr>

    <div class="col-lg-6">
        <label for='id_description'>Job Description:</label>
        <p>{{ form.description}}</p>
        
        <p>{{ form.file}}</p>
    </div>
    <div class="col-lg-6">
    
        <label for='id_tips'>Tips:</label>
        <p>{{ form.tips }}</p>
        
    </div>
    <div> <input type="submit" value="submit"> </input></div>
    
    </form>
</div>
</div>
<div class="col-lg-1"></div>
</div>

{% endblock %}

first_project/positions/templates/positions/position_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="container">
  <div class="col-lg-10">
    <div class="jumbotron">
    
     <h2 style="color: #457b9d;text-align: center;">{{ position.name }}</h2>
     <div class="row" style="color:#6c757d;">
     <div class="col-lg-4"><h4><b>Client:</b> {{ position.company}}</h4></div>
     <div class="col-lg-4"><h4><b>Location:</b> {{position.location}}</h4></div>
     <div class="col-lg-4"><h4><b>AM:</b> {{position.account_manager}}</h4></div>
    </div>
    {% if position.description %}
    <hr>
    <h4 style="color:#6c757d"> <b>Job Description:</b></h4>
     <p >{{ position.description }}</p>
     <hr>
     {% endif %}

     {% if position.file %}
        <a href="{{position.file.url}}"> Download Job Description</a>
      {% endif %}        
     
   
    <div class="container">
    
    </div>
  </div>
</div>
    <div class="col-lg-2">
      <br>
      <br>
      
      <a class="btn btn-default " href="{% url 'positions:position-update' pk=position.pk %}">Update</a>
      <br>
      <br>
    <a class="btn btn-default " href="{% url 'positions:delete' pk=position.pk %}">Delete </a>
    
    </div>
</div>


{% endblock %}

first_project/positions/templates/positions/position_list.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
     <h2 style="text-align: center;"> Welcome to the Positions Board!</h2>
     <!-- <h2> Latest Announcements</h2> -->
     {% for client in clients %}
        <h3> {{ client.name }}</h3>
   
            <table class="table table-hover" id='result-table'>
                <thead>
                    <th class="col-lg-6">Position </th>
                    <th class="col-lg-2">Location</th>
                    <th class="col-lg-2">Account Manager</th>
                    <th class="col-lg-2">Recruiter</th>
                </thead>
            {% for position in position_list %} 
             {% if position.company.name == client.name %}
                <tr>
                    <td class="col-lg-6"><a href="{{ position.get_absolute_url }}"> {{ position.name}} </a></td>
                    <td class="col-lg-2">{{ position.location}}</td>
                    <td class="col-lg-2">{{ position.account_manager}}</td>
                    <td class="col-lg-2">{{ position.recruiter}}</td>
                    <!-- <li><a href="{{ position.get_absolute_url }}">{{ position.name}}</a></li> -->
                    
                </tr>
                {% endif %}
            {% endfor %}
            </table>
        {% endfor %}
    </div>

   
    <!-- {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/cars?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/cars?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %} -->



</div>
{% endblock %}

first_project/positions/templates/positions/position_update.html
{% extends 'base_layout.html' %}
{% block content %}

<div class="container">
   
    <h2> Update the Position </h2>
    <br>
    <br>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- ['company','name','location','account_manager','recruiter','tips','description','file'] -->
    <div class="row">
        
      
        <div class="col-lg-4"><label for='id_name'>Position:     </label>  {{ form.name }}</div>
        <div class="col-lg-4"><label for='id_account_manager'>AM:   </label>{{ form.account_manager }}</div>
        <div class="col-lg-4"><label for='id_company'>Recruiter:   </label>{{ form.recruiter }}</div>
    </div>
    <br>
    <br>

    <hr>

    <div class="col-lg-6">
        <label for='id_description'>Job Description:</label>
        <p>{{ form.description}}</p>
        
        <p>{{ form.file}}</p>
    </div>
    <div class="col-lg-6">
    
        <label for='id_tips'>Tips:</label>
        <p>{{ form.tips }}</p>
        
    </div>
    <div> <input type="submit" value="submit"> </input></div>
    
    </form>
   
</div>

{% endblock %}